require_relative "boot"

require "rails"
# Only the frameworks this app actually uses — no mailers, mailboxes,
# rich text, file storage, or websockets.
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_view/railtie"
require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

# Rack middleware, required explicitly (and excluded from autoload_lib below)
# because it is referenced while the middleware stack is built at boot, before
# Zeitwerk autoloading is available.
require_relative "../lib/middleware/mcp_body_limit"

module PasteHtmlDev
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 8.1

    # Please, add to the `ignore` list any other `lib` subdirectories that do
    # not contain `.rb` files, or that should not be reloaded or eager loaded.
    # Common ones are `templates`, `generators`, or `middleware`, for example.
    config.autoload_lib(ignore: %w[assets tasks middleware])

    # Reject oversized bodies to /mcp and /oauth/register at the front of the
    # stack, before anything parses or buffers them.
    config.middleware.insert_before 0, McpBodyLimit

    # English (default) and Arabic. Fallbacks keep a half-finished Arabic
    # translation from ever breaking a page: a missing key falls back to English.
    config.i18n.available_locales = %i[ en ar ]
    config.i18n.default_locale = :en
    config.i18n.fallbacks = true

    # The CycloneDX SBOM syft generates during the Docker image build (see
    # Dockerfile), served at /.well-known/sbom.cdx.json. Deliberately OUTSIDE
    # public/: the static file server stamps a 1-year cache-control on that
    # whole directory, and a year-stale SBOM is worse than none. Absent in
    # development/test unless generated by hand; tests point this at a fixture.
    config.x.sbom_path = Rails.root.join("sbom.cdx.json")

    # Configuration for the application, engines, and railties goes here.
    #
    # These settings can be overridden in specific environments using the files
    # in config/environments, which are processed later.
    #
    # config.time_zone = "Central Time (US & Canada)"
    # config.eager_load_paths << Rails.root.join("extras")
  end
end
