# OAuth discovery documents for the MCP authorization/resource server:
# RFC 9728 (protected resource metadata) and RFC 8414 (authorization server
# metadata). Both are static JSON built exclusively from McpOauth::CONFIG --
# never from request headers, since that's the trusted issuer/resource
# identity used in audience checks (see config/initializers/mcp_oauth.rb).
#
# ActionController::API on purpose, not ApplicationController: that base
# includes the Authentication concern, whose default before_action would
# redirect these public, session-less endpoints to the login page. MCP
# clients probe them before any login has happened.
class WellKnownController < ActionController::API
  SCOPES_SUPPORTED = McpTools::ALL_SCOPES

  # The experimental discovery contract's dedicated media type for server
  # cards; the catalog advertises it and the /mcp/server-card route serves it.
  SERVER_CARD_MEDIA_TYPE = "application/mcp-server-card+json".freeze

  # The catalog/card discovery endpoints are public, cacheable JSON meant to
  # be fetched by browser-based agents from any origin.
  before_action :allow_discovery_cors, only: %i[server_card catalog]

  # RFC 9728 -- GET /.well-known/oauth-protected-resource(/mcp)
  def protected_resource
    render json: {
      resource: McpOauth::CONFIG[:resource_uri],
      authorization_servers: [ McpOauth::CONFIG[:issuer] ],
      scopes_supported: SCOPES_SUPPORTED,
      bearer_methods_supported: %w[header]
    }
  end

  # SEP-2127 (draft) MCP Server Card, served on two routes:
  #   GET /.well-known/mcp/server-card.json  (application/json -- the shape
  #       readiness checkers fetch)
  #   GET /mcp/server-card                   (application/mcp-server-card+json,
  #       the experimental contract's reserved location, linked from the catalog)
  #
  # Field names follow the registry server.json shape the SEP converged on.
  # $schema is REQUIRED by the upstream ServerCard schema and must be exactly
  # this /v1/ URL (the hosted URL 404s today -- it is an identifier, not a
  # fetch target); the test suite validates the card against a vendored pin of
  # that schema. `transport` is kept alongside `type` in the remote entry
  # because pre-convergence clients read that spelling. `capabilities` mirrors
  # McpController::SERVER_CAPABILITIES -- the card must never promise
  # prompts/resources the live server refuses.
  def server_card
    issuer = McpOauth::CONFIG[:issuer]

    expires_in 1.hour, public: true
    render json: {
      "$schema": "https://static.modelcontextprotocol.io/schemas/v1/server-card.schema.json",
      name: McpTools::SERVER_NAME,
      title: McpTools::SERVER_TITLE,
      description: "Publish, update, and organize HTML and Markdown pastes on PasteHTML as the authorized user.",
      version: McpTools::VERSION,
      websiteUrl: issuer,
      repository: { url: "https://github.com/AliOsm/pastehtml.dev", source: "github" },
      icons: [
        { src: "#{issuer}/icon.png", sizes: [ "512x512" ], mimeType: "image/png" },
        { src: "#{issuer}/icon.svg", sizes: [ "any" ], mimeType: "image/svg+xml" }
      ],
      capabilities: McpController::SERVER_CAPABILITIES,
      remotes: [
        {
          type: "streamable-http",
          transport: "streamable-http",
          url: McpOauth::CONFIG[:resource_uri],
          supportedProtocolVersions: MCP::Configuration::SUPPORTED_STABLE_PROTOCOL_VERSIONS
        }
      ],
      maintainer: { name: "Ali Hamdi Ali Fadel", email: "mcp@pastehtml.dev", url: "https://github.com/AliOsm" }
    }, content_type: params[:card_media_type] ? SERVER_CARD_MEDIA_TYPE : "application/json"
  end

  # Experimental discovery entrypoint -- GET /.well-known/mcp/catalog.json.
  # Points agents at the server card's reserved location. specVersion is
  # literally "draft" upstream; revisit when the extension stabilizes.
  def catalog
    expires_in 1.hour, public: true
    render json: {
      specVersion: "draft",
      entries: [
        {
          identifier: "urn:air:#{McpOauth::CONFIG[:host]}:mcp",
          displayName: McpTools::SERVER_TITLE,
          mediaType: SERVER_CARD_MEDIA_TYPE,
          url: "#{McpOauth::CONFIG[:issuer]}/mcp/server-card"
        }
      ]
    }
  end

  # CycloneDX SBOM -- GET /.well-known/sbom.cdx.json
  #
  # The file is generated by syft during the Docker image build (Dockerfile),
  # so it always describes exactly the lockfiles the running image was built
  # from. 404 when absent (development/test) rather than serving a stale copy.
  def sbom
    path = Rails.application.config.x.sbom_path
    return head :not_found unless path && File.file?(path)

    expires_in 1.hour, public: true
    send_file path, type: "application/json", disposition: :inline
  end

  # RFC 8414 -- GET /.well-known/oauth-authorization-server
  def authorization_server
    issuer = McpOauth::CONFIG[:issuer]

    render json: {
      issuer: issuer,
      authorization_endpoint: "#{issuer}/oauth/authorize",
      token_endpoint: "#{issuer}/oauth/token",
      registration_endpoint: "#{issuer}/oauth/register",
      revocation_endpoint: "#{issuer}/oauth/revoke",
      grant_types_supported: %w[authorization_code refresh_token],
      response_types_supported: %w[code],
      # Mandatory per RFC 8414 / the MCP spec: clients abort discovery
      # entirely if this field is missing.
      code_challenge_methods_supported: %w[S256],
      token_endpoint_auth_methods_supported: %w[none],
      scopes_supported: SCOPES_SUPPORTED
    }
  end

  private
    # The experimental discovery contract requires the catalog (and by
    # extension the card) to be fetchable cross-origin: public data, GET only,
    # no credentials involved.
    def allow_discovery_cors
      response.headers["Access-Control-Allow-Origin"] = "*"
      response.headers["Access-Control-Allow-Methods"] = "GET"
      response.headers["Access-Control-Allow-Headers"] = "Content-Type"
    end
end
